In [17]:
import numpy as np
from typing import Tuple


def sum_non_neg_diag(x):
    """
    Вернуть  сумму неотрицательных элементов на диагонали прямоугольной матрицы X. 
    Если неотрицательных элементов на диагонали нет, то вернуть -1
    """
    y = np.diag(x)[np.diag(x) >= 0]
    return np.sum(y) if y.size > 0 else -1


sum_non_neg_diag([[-1, 0, 1], [2, -1, 2], [3, 0, 9], [4, 4, 4]])

9

In [19]:
"""
Проверить, задают ли два вектора одно и то же мультимножество.
"""
def are_multisets_equal(x, y):
    x_nums, x_counts = np.unique(x, return_counts = True)
    y_nums, y_counts = np.unique(y, return_counts = True)
    if (np.shape(x_nums) != np.shape(y_nums)): return False 
    if (np.any(x_counts != y_counts)): return False 
    if (np.any(x_nums != y_nums)): return False
    return True

are_multisets_equal(x = [1, 2, 2, 4], y = [4, 2, 1, 2])

[1 2 4] [1 2 1]
[1 2 4] [1 2 1]


True

In [39]:
"""
Вернуть максимальное прозведение соседних элементов в массиве x, 
таких что хотя бы один множитель в произведении делится на 3.
Если таких произведений нет, то вернуть -1.
"""
def max_prod_mod_3(x):
    y = np.array(x)
    y = (y[1:] * y[:-1])
    y = y[y % 3 == 0]
    return y.max() if y.size > 0 else -1

max_prod_mod_3([6, 2, 0, 3, 0, 0, 5, 9, 0])
    

45

In [175]:
"""
Сложить каналы изображения с указанными весами.
"""
def convert_image(image: np.ndarray, weights: np.ndarray) -> np.ndarray:
    image = np.array(image)
    weights = np.array(weights)
    image = np.rot90(image, axes = (2, 0))
    image = np.rot90(image, axes = (1, 2))
    print(np.einsum('ijk, i -> ijk', image, weights).sum(axis = 0))
    
    
convert_image(image = [[[1, 1, 1], [2, 2, 2], [3, 3, 3]], [[4, 4, 4], [5, 5, 5], [6, 6, 6]], [[7, 7, 7], [8, 8, 8], [9, 9, 9]]], weights= [1, 2, 3])

[[ 6 12 18]
 [24 30 36]
 [42 48 54]]


In [59]:
"""
Найти скалярное произведение между векторами x и y, заданными в формате RLE.
В случае несовпадения длин векторов вернуть -1.
"""
def rle_scalar(x: np.ndarray, y: np.ndarray) -> int:
    x = np.array(x)
    y = np.array(y)
    lenx = x[:, 1].sum()
    leny = y[:, 1].sum()
    
    if lenx != leny:
        return -1
    
    new_x = np.repeat(x[:, 0], x[:, 1])
    new_y = np.repeat(y[:, 0], y[:, 1])
    
    return np.dot(new_x, new_y)
    
    

rle_scalar(x = [[11, 2], [22, 3], [3, 1]], y = [[1, 1], [0, 5]])

11

In [ ]:
np.full(i[1], i[0])
np.append(nx, [i[0]] * i[1])

In [15]:
from typing import List
"""
Вернуть  сумму неотрицательных элементов на диагонали прямоугольной матрицы X. 
Если неотрицательных элементов на диагонали нет, то вернуть -1
""" 
def sum_non_neg_diag(x: List[List[int]]) -> int:
    length = min(len(x), len(x[0]))
    diag = [x[i][i] for i in range(length) if x[i][i] >= 0]
    return sum(diag) if diag else -1

sum_non_neg_diag([[-1, 0, 1, 4], [2, -3, 2, 4], [3, 0, -3, 4], [4, 4, -4, -4]])

-1

In [29]:
def are_multisets_equal(x: List[int], y: List[int]) -> bool:
    return sorted(x) == sorted(y)

are_multisets_equal(x = [1, 2, 2, 2, 4], y = [4, 2, 1, 2])

False

In [42]:
def max_prod_mod_3(x):
    x1 = x[1:]
    x2 = x[:-1]
    prod = [x1[i] * x2[i] for i in range(0, len(x1)) if (x1[i] % 3 == 0) or (x2[i] % 3 == 0)]
    return max(prod)

max_prod_mod_3([6, 2, 0, 3, 0, 0, 5, 0, 10])

12

In [56]:
def convert_image(image: List[List[List[float]]], weights: List[float]) -> List[List[float]]:
    res = []
    for matrix in image:
        newrow = []
        for row in matrix:
            s = 0
            for i in range(len(row)):
                s += row[i] * weights[i]
            newrow.append(s)
        res.append(newrow)
    return res
        
        
        
        
        
convert_image(image = [[[1, 1, 1], [2, 2, 2], [3, 3, 3]], [[4, 4, 4], [5, 5, 5], [6, 6, 6]], [[7, 7, 7], [8, 8, 8], [9, 9, 9]]], weights= [1, 2, 3])

[[6, 12, 18], [24, 30, 36], [42, 48, 54]]

In [93]:
"""
Вычислить матрицу косинусных расстояний между объектами X и Y.
В случае равенства хотя бы одно из двух векторов 0, косинусное расстояние считать равным 1.
"""
def cosine_distance(X: np.ndarray, Y: np.ndarray) -> np.ndarray:
    X = np.array(X)
    Y = np.array(Y)
    Z = np.dot(X, Y.T)
    print(Z)
    norm_X = np.linalg.norm(X, axis = 1)
    norm_Y = np.linalg.norm(Y, axis = 1)
    print(norm_X, norm_Y)
    Z[norm_X == 0] = 1
    Z[:, norm_Y == 0] = 1
    norm_X[norm_X == 0] = 1
    norm_Y[norm_Y == 0] = 1
    print(norm_X, norm_Y)
    print(Z)
    
    
    
    print(np.outer(norm_X, norm_Y))
    return Z / (np.outer(norm_X, norm_Y))
    
    
cosine_distance(X = [[0, 0, 0], [1, 0, 0]], Y = [[1, 0, 0], [0, 1, 0], [0, 0, 1]])

[[0 0 0]
 [1 0 0]]
[0. 1.] [1. 1. 1.]
[1. 1.] [1. 1. 1.]
[[1 1 1]
 [1 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]]


array([[1., 1., 1.],
       [1., 0., 0.]])

In [99]:
"""
Вычислить матрицу косинусных расстояний между объектами X и Y. 
В случае равенства хотя бы одно из двух векторов 0, косинусное расстояние считать равным 1.
"""
def cosine_distance(X: List[List[float]], Y: List[List[float]]) -> List[List[float]]:
    res = []
    
    for i in range(len(X)):
        new_row = []
        for j in range(len(Y)):
            dist, scalar, xnorm, ynorm = [0] * 4
            for k in range(len(X[0])):
                xnorm += X[i][k] ** 2
                ynorm += Y[j][k] ** 2
                scalar += X[i][k] * Y[j][k]
            
            if xnorm and ynorm:
                dist = scalar / (xnorm * ynorm) ** (1/2)
            else:
                dist = 1
            
            new_row.append(dist)
        res.append(new_row)
    
    return res
cosine_distance(X = [[0, 0, 0], [1, 0, 0]], Y = [[1, 0, 0], [1, 1, 0], [1, 0, 1]])

[[1, 1, 1], [1.0, 0.7071067811865475, 0.7071067811865475]]